# AirBnb vs Hotels. 
## A case study, Barcelona

We will explore prices and tipology of both Airbnb data as well as Hotels data in order to get insights about the competition between both.

### Airbnb Data Cleansing

Will follow these steps we will add the data to a dataframe and plot it in a map to make sure all looks correct.

In [2]:
import pandas as pd

airbnb = pd.read_csv('./data/Airbnb Listings.csv')

airbnb.head(2)

,id,listing_url,summary,host_since,host_response_time,host_total_listings_count,latitude,longitude,is_location_exact,property_type,...,bathrooms,bedrooms,beds,bed_type,amenities,price,number_of_reviews,first_review,last_review,review_scores_rating
0,18666,https://www.airbnb.com/rooms/18666,"Apartment located near the ""Plaza de las Glori...",19/01/2010,within an hour,50.0,41.408886,2.185545,t,Apartment,...,1.0,2.0,4.0,Real Bed,"{TV,Internet,Wifi,""Air conditioning"",""Wheelcha...",$130.00,1,10/10/2015,10/10/2015,80.0
1,18674,https://www.airbnb.com/rooms/18674,110m2 apartment to rent in Barcelona. Located ...,19/01/2010,within an hour,50.0,41.404197,2.173058,t,Apartment,...,2.0,3.0,6.0,Real Bed,"{TV,Internet,Wifi,""Air conditioning"",""Wheelcha...",$140.00,5,27/05/2013,18/06/2018,85.0

In [3]:
#Lets filter the data to show only listings with Real Bed or Pull Out Sofa
airbnb['bed_type'].value_counts()

Real Bed         17625
Pull-out Sofa      112
Futon               38
Couch                8
Airbed               5
Name: bed_type, dtype: int64

In [4]:
bed_types_list = ['Real Bed', 'Pull-out Sofa']

airbnb = airbnb.loc[airbnb['bed_type'].isin(bed_types_list)]

airbnb.head(2)

,id,listing_url,summary,host_since,host_response_time,host_total_listings_count,latitude,longitude,is_location_exact,property_type,...,bathrooms,bedrooms,beds,bed_type,amenities,price,number_of_reviews,first_review,last_review,review_scores_rating
0,18666,https://www.airbnb.com/rooms/18666,"Apartment located near the ""Plaza de las Glori...",19/01/2010,within an hour,50.0,41.408886,2.185545,t,Apartment,...,1.0,2.0,4.0,Real Bed,"{TV,Internet,Wifi,""Air conditioning"",""Wheelcha...",$130.00,1,10/10/2015,10/10/2015,80.0
1,18674,https://www.airbnb.com/rooms/18674,110m2 apartment to rent in Barcelona. Located ...,19/01/2010,within an hour,50.0,41.404197,2.173058,t,Apartment,...,2.0,3.0,6.0,Real Bed,"{TV,Internet,Wifi,""Air conditioning"",""Wheelcha...",$140.00,5,27/05/2013,18/06/2018,85.0

In [5]:
#just to check
airbnb['bed_type'].value_counts()

Real Bed         17625
Pull-out Sofa      112
Name: bed_type, dtype: int64

In [6]:
#Also we need listings with at least 5 reviews during the last year
airbnb.dtypes

#we see we dont have a date column so will need to create it

id                             int64
listing_url                   object
summary                       object
host_since                    object
host_response_time            object
host_total_listings_count    float64
latitude                     float64
longitude                    float64
is_location_exact             object
property_type                 object
room_type                     object
accommodates                   int64
bathrooms                    float64
bedrooms                     float64
beds                         float64
bed_type                      object
amenities                     object
price                         object
number_of_reviews              int64
first_review                  object
last_review                   object
review_scores_rating         float64
dtype: object

In [7]:
#Create date column
airbnb['last_review'] = pd.to_datetime(airbnb['last_review'])
#airbnb.dtypes #jsut to check

#filter by last year (american notation!!) and with at least 5 reviews in total
airbnb = airbnb[(airbnb['last_review'] > '8/10/2017') & (airbnb['last_review'] < '7/10/2018') & (airbnb['number_of_reviews'] > 4) ]

#check
print (airbnb['last_review'].min())
print (airbnb['last_review'].max())
print (airbnb['number_of_reviews'].min())

2017-08-11 00:00:00
2018-07-07 00:00:00
5

In [8]:
airbnb.count()
#we almost reduced by 50% the original number of listings

id                           9251
listing_url                  9251
summary                      8957
host_since                   9249
host_response_time           8965
host_total_listings_count    9249
latitude                     9251
longitude                    9251
is_location_exact            9251
property_type                9251
room_type                    9251
accommodates                 9251
bathrooms                    9242
bedrooms                     9246
beds                         9246
bed_type                     9251
amenities                    9251
price                        9251
number_of_reviews            9251
first_review                 9250
last_review                  9251
review_scores_rating         9250
dtype: int64

In [9]:
#change prices to float 
airbnb['price'] = airbnb['price'].replace('[\$,]', '', regex=True).astype(float)

In [10]:
#export airbnb data
airbnb.to_csv('./data/Airbnb_for_analysis.csv')

### Hotels dataset from Tripadvisor

In [11]:
#read the hotels data that we will need to merge in a single dataframe
columns_list = ['Hotel Name', 'Price (USD)', 'Number of reviews', 'Reviews rating (out of 5)', 'Ranking (best value)', 'Hotel Link']
hotels_list = pd.read_csv('./data/Full Hotel list with Links.csv', header=None, names = columns_list)
columns_details = ['Hotel Address', 'Hotel Link','User Reviews Ratings','Stars Rating', 'Average reviews','Excellent reviews' ,'Poor reviews', 'Terrible reviews', 'Very Good reviews', ]
hotels_details = pd.read_csv('./data/Hotel Details.csv', skiprows=1, names = columns_details)
                             
#merge both datasets based on the h_link which is the common field
hotels = pd.merge(hotels_list, hotels_details, on='Hotel Link')
hotels.to_csv('./data/hotels_to_geocode.csv')

Once data is geocoded with ArcGIS online tools we bring it back to the notebook to proceed with the analysis, we have two new columsn with the lat and longitude for each hotel

In [12]:
#get teh data back
hotels = pd.read_csv('./data/Hotels_Joined_Geocoded.csv')
hotels.head(2)

,Hotel Name,Price (USD),Number of reviews,Reviews rating (out of 5),Ranking (best value),Hotel Link,Hotel Address,User Reviews Ratings,Stars Rating,Average reviews,Excellent reviews,Poor reviews,Terrible reviews,Very Good reviews,FID,x,y
0,Hotel Via Augusta,67.0,999,4.0,51.0,https://www.tripadvisor.com/Hotel_Review-g1874...,"Via Augusta 63 , 08006 Barcelona, Spain",193.0,4.0,55.0,104.0,13.0,5.0,140.0,1,2.151556,41.400132
1,Hotel The Serras,263.0,1057,5.0,52.0,https://www.tripadvisor.com/Hotel_Review-g1874...,"Passeig de Colom, 9 , 08002 Barcelona, Spain",1.0,5.0,5.0,750.0,2.0,0.0,51.0,2,2.181013,41.380084
2,Andante,78.0,1872,4.5,53.0,https://www.tripadvisor.com/Hotel_Review-g1874...,"Drassanes, 23-25 , Raval, Ciutat Vella08001 Ba...",108.0,3.0,60.0,514.0,12.0,9.0,373.0,3,2.172653,41.376745
3,Hotel Astoria,61.0,1282,4.0,54.0,https://www.tripadvisor.com/Hotel_Review-g1874...,"Paris, 203 , 08036 Barcelona, Spain",132.0,3.0,93.0,258.0,19.0,9.0,286.0,4,2.153568,41.393906
4,NH Sants Barcelona,77.0,1523,4.0,55.0,https://www.tripadvisor.com/Hotel_Review-g1874...,"Numancia, 74 , 08029 Barcelona, Spain",222.0,4.0,66.0,96.0,18.0,7.0,132.0,5,2.137737,41.384528

We are going to "normalize" the star ratings data so goes only from 1 to 5, there are some in between.

In [13]:
#we Will be using the cut function to create the different bins
    
hotels['Stars Rating Categories'] = pd.cut(hotels['Stars Rating'],5, labels=["1 Star Hotel", "2 Star Hotel", "3 Star Hotel", "4 Star Hotel", "5 Star Hotel"])

hotels.to_csv('./data/Hotels Merged Enriched.csv')

## Final data Visualization using CartoFrames

In [53]:
# we inizialize the carto context
import cartoframes
from cartoframes import CartoContext, BaseMap, Layer, styling
cc = CartoContext(base_url='https://natxnycdsa.carto.com', api_key='d2ec96729a519abe420c8f1696d485ba7c48047e')

#once connected we will write our dataset into our CARTO account
hotels_final = pd.read_csv('Hotels_to_Map.csv')
airbnb_final = pd.read_csv('./data/Airbnb_to_map.csv')
hotels_final.head(2)
airbnb_final.head(2)

,X1,id,listing_url,summary,host_since,host_response_time,host_total_listings_count,latitude,longitude,is_location_exact,...,bathrooms,bedrooms,beds,bed_type,amenities,price,number_of_reviews,first_review,last_review,review_scores_rating
0,2,19157,https://www.airbnb.com/rooms/19157,We offer a Room in a very well located apartme...,24/01/2010,within an hour,2.0,41.407929,2.174540,t,...,1.0,1.0,1.0,Real Bed,"{Internet,Wifi,Kitchen,""Smoking allowed"",Eleva...",30,165,18/08/2010,2018-06-23,89
1,4,25786,https://www.airbnb.com/rooms/25786,JUST GO THROUGH THE MANY REVIEWS I GOT THROUGH...,14/04/2010,within an hour,1.0,41.401452,2.156447,t,...,1.0,1.0,1.0,Real Bed,"{TV,Wifi,""Air conditioning"",Kitchen,Elevator,H...",42,191,11/08/2010,2018-06-07,95

In [ ]:
#we save the data into our carto account
cc.write(hotels_final, 'Hotels_vs_Airbnb', lnglat=('x', 'y'),overwrite=True)
cc.write(airbnb_final, 'Airbnb_BCN_filtered', lnglat=('longitude', 'latitude'),overwrite=True)

**We will create a simple map to visualize the data and will use the CARTO builder for the final product**

In [78]:
cc.map(lat=41.395527, lng=2.1749063, zoom=12)
cc.map(layers=[
    BaseMap('dark'),
    Layer('hotels_vs_airbnb', size={
            'column': 'price_usd_',
            'min': 4,
            'max': 12,
            'bin_method': 'quantiles'
        }, color = '#E30613')
    ])